### ISSUE TITLE
Login and password data are passed null

### ISSUE THREAD

**Issue by whyrmph** [canplay/BDO-Frontend#1]
Hi! I have a problem when clicking the Launcher button on BDO-Frontend, in Launcher.exe passed just null, how to fix it?
![image](https://user-images.githubusercontent.com/57942975/98449825-468deb80-2148-11eb-9eb5-3f95c46e7865.png)

**Comment by canplay** [comment]
Please provide more detailed information, such as startup sequence, operation flow, etc.

**Comment by whyrmph** [comment]
I provide a video with detailed launch steps:
[https://youtu.be/9MzWOoOborI](url)

functions and methods have not changed, I can't understand what this might be related to

**Comment by canplay** [comment]
Sorry i can't watch YouTube, try typing url "BDOLauncher://YOUR GAME PATH/bin64/BlackDesert64.exe&YOUR GAME SERVER IP&YOUR USERNAME&YOUR PASSWORD" directly into your browser to see if you can log into the game correctly

**Comment by canplay** [comment]
I submitted a new version to solve this problem, you can try it

**Comment by whyrmph** [comment]
> Sorry i can't watch YouTube, try typing url "BDOLauncher://YOUR GAME PATH/bin64/BlackDesert64.exe&YOUR GAME SERVER IP&YOUR USERNAME&YOUR PASSWORD" directly into your browser to see if you can log into the game correctly

Yes, when I address it to the address BDOLauncher://YOUR GAME PATH/bin64/BlackDesert64. exe&YOUR GAME SERVER IP&YOUR USERNAME&YOUR PASSWORD, everything is passed correctly, and when I click the Launcher button, null is passed

**Comment by whyrmph** [comment]
> I submitted a new version to solve this problem, you can try it

now undefined is passed
![image](https://user-images.githubusercontent.com/57942975/98465772-666eef00-21dc-11eb-9d9c-7e58438b01cf.png)

**Comment by whyrmph** [comment]
> Sorry i can't watch YouTube, try typing url "BDOLauncher://YOUR GAME PATH/bin64/BlackDesert64.exe&YOUR GAME SERVER IP&YOUR USERNAME&YOUR PASSWORD" directly into your browser to see if you can log into the game correctly

where will it be convenient for you to watch the video? I can upload it there for you

**Comment by canplay** [comment]
I found the problem, starting at line 169 of index.vue, and did not get the Username and Password values
